### ISSUE TITLE
Add a wall of review

### ISSUE THREAD

**Issue by tewarig** [tewarig/MeowForm#5]
Currently, meowform has around 100+ users and our users love us. so it would be great to add a wall of a review section to meow from where we display review's of developers using meowform it would be great to have a such section in meowform we can use meowforms to even submit new reviews :)

what do you need to do?

- [ ]  Make a new section on meowform home page 
- [ ] add a review card in components section
- [ ]  use that card to display the review of users 
- [ ]  for now, the reviews can be static and hardcoded :)
- [ ]  for reviews you can take them from the blog of meowform's blog  ( https://blog.gauravtewari.xyz/introducing-meowforms-build-custom-forms-with-no-backend-code-for-free-my-first-saas-product )

if you have something new or innovative in your mind please feel to share it , it would be happy to know it.

**Comment by kushalShukla-web** [comment]
can i ?

**Comment by kushalShukla-web** [comment]
so this review data is hardcoded right ?

**Comment by atom19-i** [comment]
@tewarig can you provide me .env file variables?
